Disable Yarn's hardened mode in PR previews (#3422)
We recently upgraded from Yarn 3 to Yarn 4 and started getting CI
failures for PR previews with this stacktrace:

```
Run scripts/pr-previews/builder.py pr-3420 --basepath /documentation/pr-3420
17:54:00 [INFO] Using tmpdir /tmp/tmpx5jhzhws
17:54:00 [INFO] local content files copied
17:55:55 [INFO] Docker contents extracted
17:55:55 [INFO] Starting subprocess: yarn, install
➤ YN0000: Yarn detected that the current workflow is executed from a public pull request. For safety the hardened mode has been enabled.
➤ YN0000: It will prevent malicious lockfile manipulations, in exchange for a slower install time. You can opt-out if necessary; check our documentation for more details.

➤ YN0000: · Yarn 4.9.2
➤ YN0000: ┌ Resolution step
Resolution step
➤ YN0041: @quantum/carbon-radix@npm:4.0.8::__archiveUrl=https%3A%2F%2Fna.artifactory.swg-devops.com%2Fartifactory%2Fapi%2Fnpm%2Fres-quantum-team-npm-local%2F%40quantum%2Fcarbon-radix%2F-%2F%40quantum%2Fcarbon-radix-4.0.8.tgz: Invalid authentication (as an anonymous user)
➤ YN0000: └ Completed in 6s 251ms
➤ YN0000: · Failed with errors in 6s 275ms
Error: 4 [ERROR] Subprocess failed with code 1: ['yarn', 'install']
Error: Process completed with exit code 1.
```

https://yarnpkg.com/features/security#hardened-mode explains that
hardened mode attempts to eagerly re-validate our lockfile, which will
require having the auth token set up for IBM's internal artifactory. We
cannot set that in open-source. Instead, we pre-install the dependencies
directly into the Docker image. So, we should turn off hardened mode.