Issue 5226: Fix typo in create-a-provider#providing-access-to-backends (#5611)
Fixes two typos ("qsikit" --> "qiskit" AND "Str" --> "str") in
"Providing access to backends" in "Integrate external resources with
Qiskit"
(https://quantum.cloud.ibm.com/docs/en/guides/create-a-provider).

Fixes #5226 (https://github.com/Qiskit/documentation/issues/5226)

I did NOT triage or address the separate error in the same issue about
running code under "Providing an interface for execution" with the error
NameError: na,me 'Iterable' is not defined:

In my view, the content describing the error when running the code
should be copied into a new Issue with its own Issue number. A debug
error and a typo error require different types of triage. I would feel
more comfortable if someone else addressed the debug error content.

Signed-off-by: Bryan Johnson <bryan.a.johnson@gmail.com>