Fix sphinx-alt-text-validator encoding error in Windows (#2453)
The linter had an encoding error when reading the files in Windows:

```bash
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\qiskit-ibm-runtime\tools\verify_images.py", line 108, in <module>
    main()
  File "c:\qiskit-ibm-runtime\tools\verify_images.py", line 83, in main
    results = pool.map(validate_image, files)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\multiprocessing\pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\multiprocessing\pool.py", line 774, in get
    raise self._value
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1420: character maps to <undefined>
```